version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Dependabot]"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
