name: Ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-dependecies:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci --force
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: ['install-dependecies']
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci --force

      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: ['install-dependecies']
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci --force

      - name: Prepare
        run: npm run dev:prepare

      - name: Run tests
        run: npm run test

